In [1]:
'''Tf IDF with Cosine Distence'''

'Tf IDF with Cosine Distence'

In [2]:
import pandas as pd
train_csv='C://Users//bilwa//code//Notebooks//que.csv'

df=pd.read_csv(train_csv)
print(len(df.index))
X=df[['Sentence1','Sentence2']]
Y=df['Score']

x1=[]
x2=[]
for index, row in df.iterrows():
    try:
        temp1=preprocess_string( remove_stopwords(row['Sentence1']))
        temp2=preprocess_string( remove_stopwords(row['Sentence2']))
        x1.append(temp1)
        x2.append(temp2)
    except:
        continue

1424

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer 

tfidf_vectorizer=TfidfVectorizer(use_idf=True)

tfidf_vectorizer_vectors=tfidf_vectorizer.fit_transform(df['Sentence1'].tolist()+df['Sentence2'].tolist())

In [17]:
first_vector_tfidfvectorizer=tfidf_vectorizer_vectors[1]
df1 = pd.DataFrame(first_vector_tfidfvectorizer.T.todense(), index=tfidf_vectorizer.get_feature_names(), columns=["tfidf"])
df1.sort_values(by=["tfidf"],ascending=False)

                  tfidf
650            0.419207
inched         0.372713
point          0.316967
laced          0.280132
ixic           0.273974
technology     0.268483
11             0.257947
composite      0.248345
down           0.241788
nasdaq         0.227771
index          0.220199
or             0.176281
percent        0.163788
to             0.098755
the            0.067591
payroll        0.000000
payrolls       0.000000
pc             0.000000
pcts           0.000000
pcs            0.000000
payment        0.000000
pdas           0.000000
peace          0.000000
payments       0.000000
000            0.000000
payload        0.000000
pay            0.000000
paul           0.000000
patton         0.000000
peacefully     0.000000
...                 ...
energetic      0.000000
enforce        0.000000
entrenched     0.000000
enforcement    0.000000
entree         0.000000
entrance       0.000000
entitled       0.000000
entire         0.000000
entice         0.000000
entertainment  0.000000
entertainer    0.000000
enterprise     0.000000
entering       0.000000
entered        0.000000
enter          0.000000
enron          0.000000
enrolled       0.000000
enough         0.000000
enmeshed       0.000000
enlists        0.000000
enjoyed        0.000000
enjoy          0.000000
english        0.000000
england        0.000000
engineering    0.000000
engineered     0.000000
engine         0.000000
engaged        0.000000
engage         0.000000
zuccarini      0.000000

[7484 rows x 1 columns]